package com.yeshtech.coolingsystem.util;

public interface LabelConstants {

	public String DATA_CENTER_OPTIONS = "DATA_CENTER_OPTIONS";
	public String LAYOUT_CANCEL = "LAYOUT_CANCEL";
	public String LAYOUT_SAVE = "LAYOUT_SAVE";
	public String LAYOUT_MENU_RUN = "LAYOUT_MENU_RUN";
	public String LAYOUT_MENU_IO = "LAYOUT_MENU_IO";
	public String LAYOUT_MENU_LUMPS_PATH = "LAYOUT_MENU_LUMPS_PATH";
	public String LAYOUT_MENU_SOLUTION = "LAYOUT_MENU_SOLUTION";
	public String LAYOUT_MENU_CONSTANTS = "LAYOUT_MENU_CONSTANTS";
	public String LAYOUT_MENU_FANS_SERVERS = "LAYOUT_MENU_FANS_SERVERS";
	public String LAYOUT_MENU_DATA_CENTER = "LAYOUT_MENU_DATA_CENTER";
	public String LAYOUT_MENU_EXTERNAL = "LAYOUT_MENU_EXTERNAL";

	// for cooling center main screen
	public String COOLING_CENTER = "COOLING_CENTER";
	public String COOLING_CENTER_FILE = "COOLING_CENTER_FILE";
	public String COOLING_CENTER_OPTIONS = "COOLING_CENTER_OPTIONS";
	public String COOLING_CENTER_EXECUTE = "COOLING_CENTER_EXECUTE";
	public String COOLING_CENTER_HELP = "COOLING_CENTER_HELP";
	public String COOLING_CENTER_FILE_OPEN_PROJECT = "COOLING_CENTER_FILE_OPEN_PROJECT";
	public String COOLING_CENTER_FILE_NEW_PROJECT = "COOLING_CENTER_FILE_NEW_PROJECT";
	public String COOLING_CENTER_FILE_SAVE_PROJECT = "COOLING_CENTER_FILE_SAVE_PROJECT";
	public String COOLING_CENTER_EXECUTE_RUN = "COOLING_CENTER_EXECUTE_RUN";
	public String COOLING_CENTER_EXECUTE_POST_PROCESS = "COOLING_CENTER_EXECUTE_POST_PROCESS";
	public String COOLING_CENTER_HELP_VTAS_MANUAL = "COOLING_CENTER_HELP_VTAS_MANUAL";
	public String COOLING_CENTER_HELP_ABOUT = "COOLING_CENTER_HELP_ABOUT";

	// for run layout
	public String LAYOUT_RUN_SIMULATION_TYPE = "LAYOUT_RUN_SIMULATION_TYPE";
	public String LAYOUT_RUN_STEADY = "LAYOUT_RUN_STEADY";
	public String LAYOUT_RUN_TRANSIENT = "LAYOUT_RUN_TRANSIENT";
	public String LAYOUT_RUN_TRANSIENT_PARAMETER = "LAYOUT_RUN_TRANSIENT_PARAMETER";
	public String LAYOUT_RUN_FINAL_STEP = "LAYOUT_RUN_FINAL_STEP";
	public String LAYOUT_RUN_FINAL_TIME = "LAYOUT_RUN_FINAL_TIME";
	public String LAYOUT_RUN_TIME_STEP_VALUE = "LAYOUT_RUN_TIME_STEP_VALUE";
	public String LAYOUT_RUN_RESTART_FILE_NAME = "LAYOUT_RUN_RESTART_FILE_NAME";
	public String LAYOUT_RUN_OVERRITE_COMPONENT = "LAYOUT_RUN_OVERRITE_COMPONENT";
	public String LAYOUT_RUN_FINAL_TIME_UNIT ="LAYOUT_RUN_FINAL_TIME_UNIT";

	// for io layout
	public String LAYOUT_IO_NOTIFY_EVERY = "LAYOUT_IO_NOTIFY_EVERY";
	public String LAYOUT_IO_STEPS = "LAYOUT_IO_STEPS";
	public String LAYOUT_IO_INFORMATION_LEVEL = "LAYOUT_IO_INFORMATION_LEVEL";
	public String LAYOUT_IO_PRINT_RESULTS = "LAYOUT_IO_PRINT_RESULTS";
	public String LAYOUT_IO_PRINT_CRITERION = "LAYOUT_IO_PRINT_CRITERION";
	public String LAYOUT_IO_PRINT_EVERY = "LAYOUT_IO_PRINT_EVERY";
	public String LAYOUT_IO_S = "LAYOUT_IO_S";
	public String LAYOUT_IO_BASE_NAME = "LAYOUT_IO_BASE_NAME";
	public String LAYOUT_IO_NUMBER_OF_STEPS = "LAYOUT_IO_NUMBER_OF_STEPS";

	// for Lumps And Paths layout
	public String LAYOUT_LUMPS_PATHS_ADD_PRINTED_LUMPS = "LAYOUT_LUMPS_PATHS_ADD_PRINTED_LUMPS";
	public String LAYOUT_LUMPS_PATHS_ADD_PRINTED_PATH = "LAYOUT_LUMPS_PATHS_ADD_PRINTED_PATH";
	public String LAYOUT_LUMPS_PATHS_PRINTED_LUMPS = "LAYOUT_LUMPS_PATHS_PRINTED_LUMPS";
	public String LAYOUT_LUMPS_PATHS_PRINTED_PATHS = "LAYOUT_LUMPS_PATHS_PRINTED_PATHS";

	// For Solution layout
	public String LAYOUT_SOLUTION_SOLUTION_METHOD = "LAYOUT_SOLUTION_SOLUTION_METHOD";
	public String LAYOUT_SOLUTION_GLOBAL_SOLUTION = "LAYOUT_SOLUTION_GLOBAL_SOLUTION";
	public String LAYOUT_SOLUTION_IMPLISIT = "LAYOUT_SOLUTION_IMPLISIT";
	public String LAYOUT_SOLUTION_EXPLISIT = "LAYOUT_SOLUTION_EXPLISIT";
	public String LAYOUT_SOLUTION_GLOBAL_RELAXATION_PARAMETER = "LAYOUT_SOLUTION_GLOBAL_RELAXATION_PARAMETER";
	public String LAYOUT_SOLUTION_GLOBAL_SOLUTION_TOLERANCE = "LAYOUT_SOLUTION_GLOBAL_SOLUTION_TOLERANCE";
	public String LAYOUT_SOLUTION_MAX_NO_OF_GLOBAL_ITERATION = "LAYOUT_SOLUTION_MAX_NO_OF_GLOBAL_ITERATION";
	public String LAYOUT_SOLUTION_FLOW_SOLUTION = "LAYOUT_SOLUTION_FLOW_SOLUTION";
	public String LAYOUT_SOLUTION_FLOW_RELAXATION_PARAMETER = "LAYOUT_SOLUTION_FLOW_RELAXATION_PARAMETER";
	public String LAYOUT_SOLUTION_INITIAL_FLOW_RATE = "LAYOUT_SOLUTION_INITIAL_FLOW_RATE";
	public String LAYOUT_SOLUTION_M_3_S = "LAYOUT_SOLUTION_M_3_S";
	public String LAYOUT_SOLUTION_FLOW_SOLUTION_TOLERANCE = "LAYOUT_SOLUTION_FLOW_SOLUTION_TOLERANCE";
	public String LAYOUT_SOLUTION_ZERO_FLOOR_FLOW_VALUE = "LAYOUT_SOLUTION_ZERO_FLOOR_FLOW_VALUE";
	public String LAYOUT_SOLUTION_MAX_NO_OF_FLOW_ITERATION = "LAYOUT_SOLUTION_MAX_NO_OF_FLOW_ITERATION";
	public String LAYOUT_SOLUTION_MIN_ALLOWABLE_FLOW_RATE = "LAYOUT_SOLUTION_MIN_ALLOWABLE_FLOW_RATE";

	// for Constants layout
	public String LAYOUT_CONSTANTS_WATER_PROPERTIES = "LAYOUT_CONSTANTS_WATER_PROPERTIES";
	public String LAYOUT_CONSTANTS_AIR_PROPERTIES = "LAYOUT_CONSTANTS_AIR_PROPERTIES";
	public String LAYOUT_CONSTANTS_SPECIFIC_HEAT = "LAYOUT_CONSTANTS_SPECIFIC_HEAT";
	public String LAYOUT_CONSTANTS_DENSITY = "LAYOUT_CONSTANTS_DENSITY";
	public String LAYOUT_CONSTANTS_FORMATION_OF_WATER = "LAYOUT_CONSTANTS_FORMATION_OF_WATER";
	public String LAYOUT_CONSTANTS_GRAVITATIONAL_ACCELERATION = "LAYOUT_CONSTANTS_GRAVITATIONAL_ACCELERATION";
	public String LAYOUT_CONSTANTS_IDEAL_GAS_CONSTANT ="LAYOUT_CONSTANTS_IDEAL_GAS_CONSTANT";
	public String LAYOUT_CONSTANTS_J_KG_K = "LAYOUT_CONSTANTS_J_KG_K";
	public String LAYOUT_CONSTANTS_KG_M_3 = "LAYOUT_CONSTANTS_KG_M_3";
	public String LAYOUT_CONSTANTS_J_KG = "LAYOUT_CONSTANTS_J_KG";
	public String LAYOUT_CONSTANTS_M_S_2 = "LAYOUT_CONSTANTS_M_S_2";

	// for Fan & Server layout
	public String LAYOUT_FAN_SERVER_ADD_FAN = "LAYOUT_FAN_SERVER_ADD_FAN";
	public String LAYOUT_FAN_SERVER_ADD_SERVER = "LAYOUT_FAN_SERVER_ADD_SERVER";
	public String LAYOUT_FAN_SERVER_CREATED_FANS = "LAYOUT_FAN_SERVER_CREATED_FANS";
	public String LAYOUT_FAN_SERVER_CREATED_SERVER = "LAYOUT_FAN_SERVER_CREATED_SERVER";

	// for data center layout
	public String LAYOUT_DATA_CENTER_DATA_CENTER_MODEL = "LAYOUT_DATA_CENTER_DATA_CENTER_MODEL";
	public String LAYOUT_DATA_CENTER_GENERATION_1_PARAMETER = "LAYOUT_DATA_CENTER_GENERATION_1_PARAMETER";
	public String LAYOUT_DATA_CENTER_GENERATION_1 = "LAYOUT_DATA_CENTER_GENERATION_1";
	public String LAYOUT_DATA_CENTER_GENERATION_2 = "LAYOUT_DATA_CENTER_GENERATION_2";
	public String LAYOUT_DATA_CENTER_TOTAL_HEAT_GAIN = "LAYOUT_DATA_CENTER_TOTAL_HEAT_GAIN";
	public String LAYOUT_DATA_CENTER_TIME_CURVE = "LAYOUT_DATA_CENTER_TIME_CURVE";
	public String LAYOUT_DATA_CENTER_GENERATION_2_PARAMETER = "LAYOUT_DATA_CENTER_GENERATION_2_PARAMETER";
	public String LAYOUT_DATA_CENTER_DATA_CENTER_DIMENSIONS = "LAYOUT_DATA_CENTER_DATA_CENTER_DIMENSIONS";
	public String LAYOUT_DATA_CENTER_EXTERNAL_HEAT_GAIN = "LAYOUT_DATA_CENTER_EXTERNAL_HEAT_GAIN";
	public String LAYOUT_DATA_CENTER_NO_OF_RACKS = "LAYOUT_DATA_CENTER_NO_OF_RACKS";
	public String LAYOUT_DATA_CENTER_R_EXTERNAL_EQUIP = "LAYOUT_DATA_CENTER_R_EXTERNAL_EQUIP";
	public String LAYOUT_DATA_CENTER_LAYOUT = "LAYOUT_DATA_CENTER_LAYOUT";
	public String LAYOUT_DATA_CENTER_K_W = "LAYOUT_DATA_CENTER_K_W";
	public String LAYOUT_DATA_CENTER_FLOOR_LEAK = "LAYOUT_DATA_CENTER_FLOOR_LEAK";
	public String LAYOUT_DATA_CENTER_CEILING_LEAK = "LAYOUT_DATA_CENTER_CEILING_LEAK";
	public String LAYOUT_DATA_CENTER_FLOOR_OPEN = "LAYOUT_DATA_CENTER_FLOOR_OPEN";
	public String LAYOUT_DATA_CENTER_CEILING_OPEN = "LAYOUT_DATA_CENTER_CEILING_OPEN";
	public String LAYOUT_DATA_CENTER_X_DIMENSION = "LAYOUT_DATA_CENTER_X_DIMENSION";
	public String LAYOUT_DATA_CENTER_Y_DIMENSION = "LAYOUT_DATA_CENTER_Y_DIMENSION";
	public String LAYOUT_DATA_CENTER_Z_DIMENSION = "LAYOUT_DATA_CENTER_Z_DIMENSION";
	public String LAYOUT_DATA_CENTER_SUBFLOOR_PLENUM = "LAYOUT_DATA_CENTER_SUBFLOOR_PLENUM";
	public String LAYOUT_DATA_CENTER_RETURN_PLENUM = "LAYOUT_DATA_CENTER_RETURN_PLENUM";
	public String LAYOUT_DATA_CENTER_M = "LAYOUT_DATA_CENTER_M";
	public String LAYOUT_DATA_CENTER_W = "LAYOUT_DATA_CENTER_W";

	// for external layout
	public String LAYOUT_EXTERNAL_TEMPERATURE = "LAYOUT_EXTERNAL_TEMPERATURE";
	public String LAYOUT_EXTERNAL_C = "LAYOUT_EXTERNAL_C";
	public String LAYOUT_EXTERNAL_TIMECURVE = "LAYOUT_EXTERNAL_TIMECURVE";
	public String LAYOUT_EXTERNAL_AIR_HUMIDITY = "LAYOUT_EXTERNAL_AIR_HUMIDITY";
	public String LAYOUT_EXTERNAL_RELATIVE_HUMIDITY = "LAYOUT_EXTERNAL_RELATIVE_HUMIDITY";
	public String LAYOUT_EXTERNAL_DUE_POINT = "LAYOUT_EXTERNAL_DUE_POINT";
	public String LAYOUT_EXTERNAL_WET_BULB = "LAYOUT_EXTERNAL_WET_BULB";
	public String LAYOUT_EXTERNAL_WATER_TEMPERATURE = "LAYOUT_EXTERNAL_WATER_TEMPERATURE";

	public String LAYOUT_PRINTED_LUMPS_NEW_PRINTED_LUMPS = "LAYOUT_PRINTED_LUMPS_NEW_PRINTED_LUMPS";
	public String LAYOUT_PRINTED_LUMPS_NAME_OF_THE_LUMP = "LAYOUT_PRINTED_LUMPS_NAME_OF_THE_LUMP";
	public String LAYOUT_PRINTED_PATHS_NEW_PRINTED_PATHS = "LAYOUT_PRINTED_PATHS_NEW_PRINTED_PATHS";
	public String LAYOUT_PRINTED_PATHS_NAME_OF_THE_PATH = "LAYOUT_PRINTED_PATHS_NAME_OF_THE_PATH";
}
