package com.yeshtech.coolingsystem.util;

public interface LabelConstants {

	public String DATA_CENTER_OPTIONS = "DATA_CENTER_OPTIONS";
	public String LAYOUT_CANCEL = "LAYOUT_CANCEL";
	public String LAYOUT_SAVE = "LAYOUT_SAVE";
	public String LAYOUT_MENU_RUN = "LAYOUT_MENU_RUN";
	public String LAYOUT_MENU_IO = "LAYOUT_MENU_IO";
	public String LAYOUT_MENU_LUMPS_PATH = "LAYOUT_MENU_LUMPS_PATH";
	public String LAYOUT_MENU_SOLUTION = "LAYOUT_MENU_SOLUTION";
	public String LAYOUT_MENU_CONSTANTS = "LAYOUT_MENU_CONSTANTS";
	public String LAYOUT_MENU_FANS_SERVERS = "LAYOUT_MENU_FANS_SERVERS";
	public String LAYOUT_MENU_DATA_CENTER = "LAYOUT_MENU_DATA_CENTER";
	public String LAYOUT_MENU_EXTERNAL = "LAYOUT_MENU_EXTERNAL";

	// for cooling center main screen
	public String COOLING_CENTER = "COOLING_CENTER";
	public String COOLING_CENTER_FILE = "COOLING_CENTER_FILE";
	public String COOLING_CENTER_OPTIONS = "COOLING_CENTER_OPTIONS";
	public String COOLING_CENTER_EXECUTE = "COOLING_CENTER_EXECUTE";
	public String COOLING_CENTER_HELP = "COOLING_CENTER_HELP";
	public String COOLING_CENTER_FILE_OPEN_PROJECT = "COOLING_CENTER_FILE_OPEN_PROJECT";
	public String COOLING_CENTER_FILE_NEW_PROJECT = "COOLING_CENTER_FILE_NEW_PROJECT";
	public String COOLING_CENTER_FILE_SAVE_PROJECT = "COOLING_CENTER_FILE_SAVE_PROJECT";
	public String COOLING_CENTER_EXECUTE_RUN = "COOLING_CENTER_EXECUTE_RUN";
	public String COOLING_CENTER_EXECUTE_POST_PROCESS = "COOLING_CENTER_EXECUTE_POST_PROCESS";
	public String COOLING_CENTER_HELP_VTAS_MANUAL = "COOLING_CENTER_HELP_VTAS_MANUAL";
	public String COOLING_CENTER_HELP_ABOUT = "COOLING_CENTER_HELP_ABOUT";

	// for run layout
	public String LAYOUT_RUN_SIMULATION_TYPE = "LAYOUT_RUN_SIMULATION_TYPE";
	public String LAYOUT_RUN_STEADY = "LAYOUT_RUN_STEADY";
	public String LAYOUT_RUN_TRANSIENT = "LAYOUT_RUN_TRANSIENT";
	public String LAYOUT_RUN_TRANSIENT_PARAMETER = "LAYOUT_RUN_TRANSIENT_PARAMETER";
	public String LAYOUT_RUN_FINAL_STEP = "LAYOUT_RUN_FINAL_STEP";
	public String LAYOUT_RUN_FINAL_TIME = "LAYOUT_RUN_FINAL_TIME";
	public String LAYOUT_RUN_TIME_STEP_VALUE = "LAYOUT_RUN_TIME_STEP_VALUE";
	public String LAYOUT_RUN_RESTART_FILE_NAME = "LAYOUT_RUN_RESTART_FILE_NAME";
	public String LAYOUT_RUN_OVERRITE_COMPONENT = "LAYOUT_RUN_OVERRITE_COMPONENT";
	public String LAYOUT_RUN_FINAL_TIME_UNIT ="LAYOUT_RUN_FINAL_TIME_UNIT";

	// for io layout
	public String LAYOUT_IO_NOTIFY_EVERY = "LAYOUT_IO_NOTIFY_EVERY";
	public String LAYOUT_IO_STEPS = "LAYOUT_IO_STEPS";
	public String LAYOUT_IO_INFORMATION_LEVEL = "LAYOUT_IO_INFORMATION_LEVEL";
	public String LAYOUT_IO_PRINT_RESULTS = "LAYOUT_IO_PRINT_RESULTS";
	public String LAYOUT_IO_PRINT_CRITERION = "LAYOUT_IO_PRINT_CRITERION";
	public String LAYOUT_IO_PRINT_EVERY = "LAYOUT_IO_PRINT_EVERY";
	public String LAYOUT_IO_S = "LAYOUT_IO_S";
	public String LAYOUT_IO_BASE_NAME = "LAYOUT_IO_BASE_NAME";
	public String LAYOUT_IO_NUMBER_OF_STEPS = "LAYOUT_IO_NUMBER_OF_STEPS";

	// for Lumps And Paths layout
	public String LAYOUT_LUMPS_PATHS_ADD_PRINTED_LUMPS = "LAYOUT_LUMPS_PATHS_ADD_PRINTED_LUMPS";
	public String LAYOUT_LUMPS_PATHS_ADD_PRINTED_PATH = "LAYOUT_LUMPS_PATHS_ADD_PRINTED_PATH";
	public String LAYOUT_LUMPS_PATHS_PRINTED_LUMPS = "LAYOUT_LUMPS_PATHS_PRINTED_LUMPS";
	public String LAYOUT_LUMPS_PATHS_PRINTED_PATHS = "LAYOUT_LUMPS_PATHS_PRINTED_PATHS";

	// For Solution layout
	public String LAYOUT_SOLUTION_SOLUTION_METHOD = "LAYOUT_SOLUTION_SOLUTION_METHOD";
	public String LAYOUT_SOLUTION_GLOBAL_SOLUTION = "LAYOUT_SOLUTION_GLOBAL_SOLUTION";
	public String LAYOUT_SOLUTION_IMPLISIT = "LAYOUT_SOLUTION_IMPLISIT";
	public String LAYOUT_SOLUTION_EXPLISIT = "LAYOUT_SOLUTION_EXPLISIT";
	public String LAYOUT_SOLUTION_GLOBAL_RELAXATION_PARAMETER = "LAYOUT_SOLUTION_GLOBAL_RELAXATION_PARAMETER";
	public String LAYOUT_SOLUTION_GLOBAL_SOLUTION_TOLERANCE = "LAYOUT_SOLUTION_GLOBAL_SOLUTION_TOLERANCE";
	public String LAYOUT_SOLUTION_MAX_NO_OF_GLOBAL_ITERATION = "LAYOUT_SOLUTION_MAX_NO_OF_GLOBAL_ITERATION";
	public String LAYOUT_SOLUTION_FLOW_SOLUTION = "LAYOUT_SOLUTION_FLOW_SOLUTION";
	public String LAYOUT_SOLUTION_FLOW_RELAXATION_PARAMETER = "LAYOUT_SOLUTION_FLOW_RELAXATION_PARAMETER";
	public String LAYOUT_SOLUTION_INITIAL_FLOW_RATE = "LAYOUT_SOLUTION_INITIAL_FLOW_RATE";
	public String LAYOUT_SOLUTION_M_3_S = "LAYOUT_SOLUTION_M_3_S";
	public String LAYOUT_SOLUTION_FLOW_SOLUTION_TOLERANCE = "LAYOUT_SOLUTION_FLOW_SOLUTION_TOLERANCE";
	public String LAYOUT_SOLUTION_ZERO_FLOOR_FLOW_VALUE = "LAYOUT_SOLUTION_ZERO_FLOOR_FLOW_VALUE";
	public String LAYOUT_SOLUTION_MAX_NO_OF_FLOW_ITERATION = "LAYOUT_SOLUTION_MAX_NO_OF_FLOW_ITERATION";
	public String LAYOUT_SOLUTION_MIN_ALLOWABLE_FLOW_RATE = "LAYOUT_SOLUTION_MIN_ALLOWABLE_FLOW_RATE";

	// for Constants layout
	public String LAYOUT_CONSTANTS_WATER_PROPERTIES = "LAYOUT_CONSTANTS_WATER_PROPERTIES";
	public String LAYOUT_CONSTANTS_AIR_PROPERTIES = "LAYOUT_CONSTANTS_AIR_PROPERTIES";
	public String LAYOUT_CONSTANTS_SPECIFIC_HEAT = "LAYOUT_CONSTANTS_SPECIFIC_HEAT";
	public String LAYOUT_CONSTANTS_DENSITY = "LAYOUT_CONSTANTS_DENSITY";
	public String LAYOUT_CONSTANTS_FORMATION_OF_WATER = "LAYOUT_CONSTANTS_FORMATION_OF_WATER";
	public String LAYOUT_CONSTANTS_GRAVITATIONAL_ACCELERATION = "LAYOUT_CONSTANTS_GRAVITATIONAL_ACCELERATION";
	public String LAYOUT_CONSTANTS_IDEAL_GAS_CONSTANT ="LAYOUT_CONSTANTS_IDEAL_GAS_CONSTANT";
	public String LAYOUT_CONSTANTS_J_KG_K = "LAYOUT_CONSTANTS_J_KG_K";
	public String LAYOUT_CONSTANTS_KG_M_3 = "LAYOUT_CONSTANTS_KG_M_3";
	public String LAYOUT_CONSTANTS_J_KG = "LAYOUT_CONSTANTS_J_KG";
	public String LAYOUT_CONSTANTS_M_S_2 = "LAYOUT_CONSTANTS_M_S_2";

	// for Fan & Server layout
	public String LAYOUT_FAN_SERVER_ADD_FAN = "LAYOUT_FAN_SERVER_ADD_FAN";
	public String LAYOUT_FAN_SERVER_ADD_SERVER = "LAYOUT_FAN_SERVER_ADD_SERVER";
	public String LAYOUT_FAN_SERVER_CREATED_FANS = "LAYOUT_FAN_SERVER_CREATED_FANS";
	public String LAYOUT_FAN_SERVER_CREATED_SERVER = "LAYOUT_FAN_SERVER_CREATED_SERVER";

	// for data center layout
	public String LAYOUT_DATA_CENTER_DATA_CENTER_MODEL = "LAYOUT_DATA_CENTER_DATA_CENTER_MODEL";
	public String LAYOUT_DATA_CENTER_GENERATION_1_PARAMETER = "LAYOUT_DATA_CENTER_GENERATION_1_PARAMETER";
	public String LAYOUT_DATA_CENTER_GENERATION_1 = "LAYOUT_DATA_CENTER_GENERATION_1";
	public String LAYOUT_DATA_CENTER_GENERATION_2 = "LAYOUT_DATA_CENTER_GENERATION_2";
	public String LAYOUT_DATA_CENTER_TOTAL_HEAT_GAIN = "LAYOUT_DATA_CENTER_TOTAL_HEAT_GAIN";
	public String LAYOUT_DATA_CENTER_TIME_CURVE = "LAYOUT_DATA_CENTER_TIME_CURVE";
	public String LAYOUT_DATA_CENTER_GENERATION_2_PARAMETER = "LAYOUT_DATA_CENTER_GENERATION_2_PARAMETER";
	public String LAYOUT_DATA_CENTER_DATA_CENTER_DIMENSIONS = "LAYOUT_DATA_CENTER_DATA_CENTER_DIMENSIONS";
	public String LAYOUT_DATA_CENTER_EXTERNAL_HEAT_GAIN = "LAYOUT_DATA_CENTER_EXTERNAL_HEAT_GAIN";
	public String LAYOUT_DATA_CENTER_NO_OF_RACKS = "LAYOUT_DATA_CENTER_NO_OF_RACKS";
	public String LAYOUT_DATA_CENTER_R_EXTERNAL_EQUIP = "LAYOUT_DATA_CENTER_R_EXTERNAL_EQUIP";
	public String LAYOUT_DATA_CENTER_LAYOUT = "LAYOUT_DATA_CENTER_LAYOUT";
	public String LAYOUT_DATA_CENTER_K_W = "LAYOUT_DATA_CENTER_K_W";
	public String LAYOUT_DATA_CENTER_FLOOR_LEAK = "LAYOUT_DATA_CENTER_FLOOR_LEAK";
	public String LAYOUT_DATA_CENTER_CEILING_LEAK = "LAYOUT_DATA_CENTER_CEILING_LEAK";
	public String LAYOUT_DATA_CENTER_FLOOR_OPEN = "LAYOUT_DATA_CENTER_FLOOR_OPEN";
	public String LAYOUT_DATA_CENTER_CEILING_OPEN = "LAYOUT_DATA_CENTER_CEILING_OPEN";
	public String LAYOUT_DATA_CENTER_X_DIMENSION = "LAYOUT_DATA_CENTER_X_DIMENSION";
	public String LAYOUT_DATA_CENTER_Y_DIMENSION = "LAYOUT_DATA_CENTER_Y_DIMENSION";
	public String LAYOUT_DATA_CENTER_Z_DIMENSION = "LAYOUT_DATA_CENTER_Z_DIMENSION";
	public String LAYOUT_DATA_CENTER_SUBFLOOR_PLENUM = "LAYOUT_DATA_CENTER_SUBFLOOR_PLENUM";
	public String LAYOUT_DATA_CENTER_RETURN_PLENUM = "LAYOUT_DATA_CENTER_RETURN_PLENUM";
	public String LAYOUT_DATA_CENTER_M = "LAYOUT_DATA_CENTER_M";
	public String LAYOUT_DATA_CENTER_W = "LAYOUT_DATA_CENTER_W";

	// for external layout
	public String LAYOUT_EXTERNAL_TEMPERATURE = "LAYOUT_EXTERNAL_TEMPERATURE";
	public String LAYOUT_EXTERNAL_C = "LAYOUT_EXTERNAL_C";
	public String LAYOUT_EXTERNAL_TIMECURVE = "LAYOUT_EXTERNAL_TIMECURVE";
	public String LAYOUT_EXTERNAL_AIR_HUMIDITY = "LAYOUT_EXTERNAL_AIR_HUMIDITY";
	public String LAYOUT_EXTERNAL_RELATIVE_HUMIDITY = "LAYOUT_EXTERNAL_RELATIVE_HUMIDITY";
	public String LAYOUT_EXTERNAL_DUE_POINT = "LAYOUT_EXTERNAL_DUE_POINT";
	public String LAYOUT_EXTERNAL_WET_BULB = "LAYOUT_EXTERNAL_WET_BULB";
	public String LAYOUT_EXTERNAL_WATER_TEMPERATURE = "LAYOUT_EXTERNAL_WATER_TEMPERATURE";

	public String LAYOUT_PRINTED_LUMPS_NEW_PRINTED_LUMPS = "LAYOUT_PRINTED_LUMPS_NEW_PRINTED_LUMPS";
	public String LAYOUT_PRINTED_LUMPS_NAME_OF_THE_LUMP = "LAYOUT_PRINTED_LUMPS_NAME_OF_THE_LUMP";
	public String LAYOUT_PRINTED_PATHS_NEW_PRINTED_PATHS = "LAYOUT_PRINTED_PATHS_NEW_PRINTED_PATHS";
	public String LAYOUT_PRINTED_PATHS_NAME_OF_THE_PATH = "LAYOUT_PRINTED_PATHS_NAME_OF_THE_PATH";
	
	public String LAYOUT_DATA_CENTER_LAYOUT_WINDOW = "LAYOUT_DATA_CENTER_LAYOUT_WINDOW";
	public String LAYOUT_DATA_CENTER_LAYOUT_ROW_NUMBER = "LAYOUT_DATA_CENTER_LAYOUT_ROW_NUMBER";
	public String LAYOUT_DATA_CENTER_LAYOUT_RACK_SPECIFICATION = "LAYOUT_DATA_CENTER_LAYOUT_RACK_SPECIFICATION";
	public String LAYOUT_DATA_CENTER_LAYOUT_EDIT_RACK = "LAYOUT_DATA_CENTER_LAYOUT_EDIT_RACK";
	public String LAYOUT_DATA_CENTER_LAYOUT_DELETE_RACK = "LAYOUT_DATA_CENTER_LAYOUT_DELETE_RACK";
	public String LAYOUT_DATA_CENTER_LAYOUT_NEW_RACK = "LAYOUT_DATA_CENTER_LAYOUT_NEW_RACK";
	public String LAYOUT_DATA_CENTER_LAYOUT_SUPPLY_HEAT_INDEX = "LAYOUT_DATA_CENTER_LAYOUT_SUPPLY_HEAT_INDEX";
	public String LAYOUT_DATA_CENTER_LAYOUT_CANCEL = "LAYOUT_DATA_CENTER_LAYOUT_CANCEL";
	public String LAYOUT_DATA_CENTER_LAYOUT_SAVE = "LAYOUT_DATA_CENTER_LAYOUT_SAVE";
	
	public String LAYOUT_NEW_FAN_WINDOW = "LAYOUT_NEW_FAN_WINDOW";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_NAME = "LAYOUT_NEW_FAN_WINDOW_FAN_NAME";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_TYPE = "LAYOUT_NEW_FAN_WINDOW_FAN_TYPE";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_TYPE_FIXED_FLOW = "LAYOUT_NEW_FAN_WINDOW_FAN_TYPE_FIXED_FLOW";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_TYPE_FIXED_PRESSURE_RISE = "LAYOUT_NEW_FAN_WINDOW_FAN_TYPE_FIXED_PRESSURE_RISE";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_TYPE_SPECIFIED_FAN_CURVE = "LAYOUT_NEW_FAN_WINDOW_FAN_TYPE_SPECIFIED_FAN_CURVE";
	public String LAYOUT_NEW_FAN_WINDOW_FIXED_FLOW_FAN = "LAYOUT_NEW_FAN_WINDOW_FIXED_FLOW_FAN";
	public String LAYOUT_NEW_FAN_WINDOW_FIXED_FLOW_FAN_FLOW_RATE = "LAYOUT_NEW_FAN_WINDOW_FIXED_FLOW_FAN_FLOW_RATE";
	public String LAYOUT_NEW_FAN_WINDOW_FIXED_FLOW_FAN_EFFICIENCY = "LAYOUT_NEW_FAN_WINDOW_FIXED_FLOW_FAN_EFFICIENCY";
	public String LAYOUT_NEW_FAN_WINDOW_FIXED_PRESSURE_RISE_FAN = "LAYOUT_NEW_FAN_WINDOW_FIXED_PRESSURE_RISE_FAN";
	public String LAYOUT_NEW_FAN_WINDOW_FIXED_PRESSURE_RISE_FAN_PRESSURE_RISE = "LAYOUT_NEW_FAN_WINDOW_FIXED_PRESSURE_RISE_FAN_PRESSURE_RISE";
	public String LAYOUT_NEW_FAN_WINDOW_FIXED_PRESSURE_RISE_FAN_EFFICIENCY = "LAYOUT_NEW_FAN_WINDOW_FIXED_PRESSURE_RISE_FAN_EFFICIENCY";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_FAN_CURVE_NAME = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_FAN_CURVE_NAME";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_REF_FLOW_HEAD = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_REF_FLOW_HEAD";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_REF_FLOWRATE = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_REF_FLOWRATE";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_STAG_FLOW_HEAD = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_STAG_FLOW_HEAD";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_REF_FANSPEED = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_REF_FANSPEED";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_MAX_FANSPEED ="LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_MAX_FANSPEED";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_MAX_EFFICIENCY = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_MAX_EFFICIENCY";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_FAN_CURVE_EFFICIENCY = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_FAN_CURVE_EFFICIENCY";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_ALPHA = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_ALPHA";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_QHATC = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_QHATC";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_HHATC = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_HHATC";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_A = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_A";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_B = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_B";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_CANCEL = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_CANCEL";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_SAVE = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_SAVE";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_M = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_M";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_M_3_S = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_M_3_S";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_RPM = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_RPM";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_PA = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_PA";
	public String LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_DEG = "LAYOUT_NEW_FAN_WINDOW_FAN_CURVE_DATA_DEG";
	
	//Labels For New Server Window
	public String LAYOUT_NEW_SERVER_WINDOW = "LAYOUT_NEW_SERVER_WINDOW";
	public String LAYOUT_NEW_SERVER_WINDOW_SERVER_NAME = "LAYOUT_NEW_SERVER_WINDOW_SERVER_NAME";
	public String LAYOUT_NEW_SERVER_WINDOW_HEAT_OUTPUT = "LAYOUT_NEW_SERVER_WINDOW_HEAT_OUTPUT";
	public String LAYOUT_NEW_SERVER_WINDOW_THERMAL_RESISTANCE = "LAYOUT_NEW_SERVER_WINDOW_THERMAL_RESISTANCE";
	public String LAYOUT_NEW_SERVER_WINDOW_W = "LAYOUT_NEW_SERVER_WINDOW_W";
	public String LAYOUT_NEW_SERVER_WINDOW_K_W = "LAYOUT_NEW_SERVER_WINDOW_K_W";
	public String LAYOUT_NEW_SERVER_WINDOW_CANCEL = "LAYOUT_NEW_SERVER_WINDOW_CANCEL";
	public String LAYOUT_NEW_SERVER_WINDOW_SAVE = "LAYOUT_NEW_SERVER_WINDOW_SAVE";
	
	//Labels for Postprocessing Window 
	public String LAYOUT_POST_PROCESSING_WINDOW = "LAYOUT_POST_PROCESSING_WINDOW";
	public String LAYOUT_POST_PROCESSING_WINDOW_RESULTS_FILE_NAME = "LAYOUT_POST_PROCESSING_WINDOW_RESULTS_FILE_NAME";
	public String LAYOUT_POST_PROCESSING_WINDOW_LOAD_RESULTS = "LAYOUT_POST_PROCESSING_WINDOW_LOAD_RESULTS";
	public String LAYOUT_POST_PROCESSING_WINDOW_CLOSE = "LAYOUT_POST_PROCESSING_WINDOW_CLOSE";
	public String LAYOUT_POST_PROCESSING_WINDOW_INPUT_PARAMETERS = "LAYOUT_POST_PROCESSING_WINDOW_INPUT_PARAMETERS";
	public String LAYOUT_POST_PROCESSING_WINDOW_EXERGY_DESTRUCTION = "LAYOUT_POST_PROCESSING_WINDOW_EXERGY_DESTRUCTION";
	public String LAYOUT_POST_PROCESSING_WINDOW_DESIGN_PARAMETERS = "LAYOUT_POST_PROCESSING_WINDOW_DESIGN_PARAMETERS";
	public String LAYOUT_POST_PROCESSING_WINDOW_GRAPHICS = "LAYOUT_POST_PROCESSING_WINDOW_GRAPHICS";
	public String LAYOUT_POST_PROCESSING_WINDOW_COMPONENT_NAME = "LAYOUT_POST_PROCESSING_WINDOW_COMPONENT_NAME";
	public String LAYOUT_POST_PROCESSING_WINDOW_COMPONENT_TYPE = "LAYOUT_POST_PROCESSING_WINDOW_COMPONENT_TYPE";
	public String LAYOUT_POST_PROCESSING_WINDOW_EXERGY_DESTRUCTION_W = "LAYOUT_POST_PROCESSING_WINDOW_EXERGY_DESTRUCTION_W";
	public String LAYOUT_POST_PROCESSING_WINDOW_COMPONENT_EXERGY_DESTRUCTION = "LAYOUT_POST_PROCESSING_WINDOW_COMPONENT_EXERGY_DESTRUCTION";
	public String LAYOUT_POST_PROCESSING_WINDOW_COLOR_SCALE_MINIMUM = "LAYOUT_POST_PROCESSING_WINDOW_COLOR_SCALE_MINIMUM";
	public String LAYOUT_POST_PROCESSING_WINDOW_COLOR_SCALE_MAXIMUM = "LAYOUT_POST_PROCESSING_WINDOW_COLOR_SCALE_MAXIMUM";
	public String LAYOUT_POST_PROCESSING_WINDOW_LOOP_MASS_FLOW_RATE = "LAYOUT_POST_PROCESSING_WINDOW_LOOP_MASS_FLOW_RATE";
	public String LAYOUT_POST_PROCESSING_WINDOW_MINIMUM_THICKNESS = "LAYOUT_POST_PROCESSING_WINDOW_MINIMUM_THICKNESS";
	public String LAYOUT_POST_PROCESSING_WINDOW_MAXIMUM_THICKNESS = "LAYOUT_POST_PROCESSING_WINDOW_MAXIMUM_THICKNESS";
	public String LAYOUT_POST_PROCESSING_WINDOW_PLOT = "LAYOUT_POST_PROCESSING_WINDOW_PLOT";
	
	//Labels for Rack Properties Window
	public String LAYOUT_RACK_PROPERTIES_WINDOW = "LAYOUT_RACK_PROPERTIES_WINDOW"; 
	public String LAYOUT_RACK_PROPERTIES_WINDOW_RACK_NAME = "LAYOUT_RACK_PROPERTIES_WINDOW_RACK_NAME";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT = "LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_HEAT_OUTPUT = "LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_HEAT_OUTPUT";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_THERMAL_RESISTANCE = "LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_THERMAL_RESISTANCE";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_TIMECURVE = "LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_TIMECURVE";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_W = "LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_W";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_K_W = "LAYOUT_RACK_PROPERTIES_WINDOW_NON_SERVER_EQUIPMENT_K_W";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION = "LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION_X_DIMENSION = "LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION_X_DIMENSION";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION_Y_DIMENSION = "LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION_Y_DIMENSION";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION_Z_DIMENSION = "LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION_Z_DIMENSION";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION_M = "LAYOUT_RACK_PROPERTIES_WINDOW_RACK_DIMENSION_M";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_NUMBER_OF_SERVER = "LAYOUT_RACK_PROPERTIES_WINDOW_NUMBER_OF_SERVER";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_CREATE_TABLE = "LAYOUT_RACK_PROPERTIES_WINDOW_CREATE_TABLE";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_SERVERS_IN_RACK = "LAYOUT_RACK_PROPERTIES_WINDOW_SERVERS_IN_RACK";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_HEAT_TIMECURVE = "LAYOUT_RACK_PROPERTIES_WINDOW_HEAT_TIMECURVE";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_FANSPEED_TIMECURVE  = "LAYOUT_RACK_PROPERTIES_WINDOW_FANSPEED_TIMECURVE";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_DELETE = "LAYOUT_RACK_PROPERTIES_WINDOW_DELETE";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_CANCEL = "LAYOUT_RACK_PROPERTIES_WINDOW_CANCEL";
	public String LAYOUT_RACK_PROPERTIES_WINDOW_SAVE = "LAYOUT_RACK_PROPERTIES_WINDOW_SAVE";
	
	//Labels for Run Window
	public String LAYOUT_RUN_WINDOW = "LAYOUT_RUN_WINDOW"; 
	public String LAYOUT_RUN_WINDOW_PREPROCESS_ONLY = "LAYOUT_RUN_WINDOW_PREPROCESS_ONLY";
	public String LAYOUT_RUN_WINDOW_INPUT_DECK_FILENAME = "LAYOUT_RUN_WINDOW_INPUT_DECK_FILENAME";
	public String LAYOUT_RUN_WINDOW_OUTPUT_RESULTS_FILENAME = "LAYOUT_RUN_WINDOW_OUTPUT_RESULTS_FILENAME";
	public String LAYOUT_RUN_WINDOW_GO = "LAYOUT_RUN_WINDOW_GO";
	public String LAYOUT_RUN_WINDOW_CLOSE = "LAYOUT_RUN_WINDOW_CLOSE";
	
	//Labels for Time Curve Specification Window
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW";
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_CURVE_NAME = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_CURVE_NAME"; 
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_NUMBER_OF_ROWS = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_NUMBER_OF_ROWS";
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_CREATE_TABLE = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_CREATE_TABLE";
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_CANCEL = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_CANCEL";
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_SAVE = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_SAVE";
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_TIMECURVE_TABLE = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_TIMECURVE_TABLE";
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_X_VALUES = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_X_VALUES";
	public String LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_Y_VALUES = "LAYOUT_TIME_CURVE_SPECIFICATION_WINDOW_Y_VALUES";

	
}
